version: '3.2'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jeagertracing
    hostname: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "9000:16686"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheusmetric
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:3.0.1
    container_name: grafanadashboards
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  grafana_data: {}

