version: '3'

services:
  # MySQL
  db:
    container_name: mysql8
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_USER: user_mysql
      MYSQL_PASSWORD: pass
    ports:
      - '3306:3306'