version: '3.7'
services:
  aws:
    image: 'localstack/localstack'
    container_name: 'localstack'
    environment:
      - SERVICES=sns
      - DEFAULT_REGION=us-east-2
      - AWS_DEFAULT_REGION=us-east-2
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566:4566'